name: Run PHP linter on push or pull request event

on: push

jobs:
  phplint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP Action
        uses: shivammathur/setup-php@2.19.1
        with:
          php-version: '7.4'

      - uses: actions/checkout@v1

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run phplint
        run: composer phplint

      - name: Run php-codesniffer
        run: composer phpcs
